### ISSUE TITLE
can I download all Github repositories from somebody else 

### ISSUE THREAD

**Issue by Sandy4321** [muhasturk/gitim#8]
I need for example download all reps from some user
for example
https://github.com/cran
or
https://github.com/llSourcell?tab=repositories
thnaks

**Comment by SamuelMarks** [comment]
Sure, my PR added support for organisations.

As an example @Sandy4321; this will clone all of [edx](https://github.com/edx)s repositories into a directory called `edx`:

    python -m gitim -o edx -d edx

**Comment by muhasturk** [comment]
Attached example in readme

**Comment by Sandy4321** [comment]
great thanks, will it also download all folders from this person repositories
https://github.com/Sandy4321?tab=repositories

**Comment by Sandy4321** [comment]
by the way this still ask username and password
why to download somebody else data I need to inter username and password
since I can download this data manually without username and password

Microsoft Windows [Version 10.0.17763.864]
(c) 2018 Microsoft Corporation. All rights reserved.

E:\Python usefull packages\gitim-master\testnvo19>python -m gitim -o muhasturk -d muhasturk

         .--.         .--. __  __   ___
  .--./) |__|         |__||  |/  `.'   `.
 /.''\  .--.     .|  .--.|   .-.  .-.   '
| |  | | |  |   .' |_ |  ||  |  |  |  |  |
 \`-' /  |  | .'     ||  ||  |  |  |  |  |
 /("'`   |  |'--.  .-'|  ||  |  |  |  |  |
 \ '---. |  |   |  |  |  ||  |  |  |  |  |
  /'""'.\|__|   |  |  |__||__|  |__|  |__|
 ||     ||      |  '.'
 '. __//       |   /
 `'----        `---`

created by "Mustafa Hasturk"
Version: 2.1.0

Username:

**Comment by Sandy4321** [comment]
I do have error
E:\Python usefull packages\gitim-master\testnvo19>python -m gitim -o muhasturk -d muhasturk

         .--.         .--. __  __   ___
  .--./) |__|         |__||  |/  `.'   `.
 /.''\  .--.     .|  .--.|   .-.  .-.   '
| |  | | |  |   .' |_ |  ||  |  |  |  |  |
 \`-' /  |  | .'     ||  ||  |  |  |  |  |
 /("'`   |  |'--.  .-'|  ||  |  |  |  |  |
 \ '---. |  |   |  |  |  ||  |  |  |  |  |
  /'""'.\|__|   |  |  |__||__|  |__|  |__|
 ||     ||      |  '.'
 '. __//       |   /
 `'----        `---`

created by "Mustafa Hasturk"
Version: 2.1.0

Username: Sandy4321
Password:
mkdir -p "muhasturk"
Traceback (most recent call last):
  File "C:\Users\sndr\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\sndr\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\sndr\Anaconda3\lib\site-packages\gitim-2.1.0-py3.6.egg\gitim.py", line 108, in <module>
  File "C:\Users\sndr\Anaconda3\lib\site-packages\gitim-2.1.0-py3.6.egg\gitim.py", line 86, in clone_main
  File "C:\Users\sndr\Anaconda3\lib\site-packages\pygithub-1.44.1-py3.6.egg\github\MainClass.py", line 259, in get_organization
  File "C:\Users\sndr\Anaconda3\lib\site-packages\pygithub-1.44.1-py3.6.egg\github\Requester.py", line 268, in requestJsonAndCheck
  File "C:\Users\sndr\Anaconda3\lib\site-packages\pygithub-1.44.1-py3.6.egg\github\Requester.py", line 279, in __check
github.GithubException.UnknownObjectException: 404 {"message": "Not Found", "documentation_url": "https://developer.github.com/v3/orgs/#get-an-organization"}

E:\Python usefull packages\gitim-master\testnvo19>

**Comment by Sandy4321** [comment]
though installation was ok
Microsoft Windows [Version 10.0.17763.864]
(c) 2018 Microsoft Corporation. All rights reserved.

E:\Python usefull packages\gitim-master\gitim-master>python setup.py install
running install
running bdist_egg
running egg_info
creating gitim.egg-info
writing gitim.egg-info\PKG-INFO
writing dependency_links to gitim.egg-info\dependency_links.txt
writing requirements to gitim.egg-info\requires.txt
writing top-level names to gitim.egg-info\top_level.txt
writing manifest file 'gitim.egg-info\SOURCES.txt'
reading manifest file 'gitim.egg-info\SOURCES.txt'
writing manifest file 'gitim.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
creating build
creating build\lib
copying gitim.py -> build\lib
creating build\bdist.win-amd64
creating build\bdist.win-amd64\egg
copying build\lib\gitim.py -> build\bdist.win-amd64\egg
byte-compiling build\bdist.win-amd64\egg\gitim.py to gitim.cpython-36.pyc
creating build\bdist.win-amd64\egg\EGG-INFO
copying gitim.egg-info\PKG-INFO -> build\bdist.win-amd64\egg\EGG-INFO
copying gitim.egg-info\SOURCES.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying gitim.egg-info\dependency_links.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying gitim.egg-info\requires.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying gitim.egg-info\top_level.txt -> build\bdist.win-amd64\egg\EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating dist
creating 'dist\gitim-2.1.0-py3.6.egg' and adding 'build\bdist.win-amd64\egg' to it
removing 'build\bdist.win-amd64\egg' (and everything under it)
Processing gitim-2.1.0-py3.6.egg
Copying gitim-2.1.0-py3.6.egg to c:\users\sndr\anaconda3\lib\site-packages
Adding gitim 2.1.0 to easy-install.pth file

Installed c:\users\sndr\anaconda3\lib\site-packages\gitim-2.1.0-py3.6.egg
Processing dependencies for gitim==2.1.0
Searching for pygithub
Reading https://pypi.org/simple/pygithub/
Downloading https://files.pythonhosted.org/packages/f4/86/7206d9b47cfdd5880081fdd1c94d9615cb6e10f4db1e98eb5b358839bc2a/PyGithub-1.44.1.tar.gz#sha256=453896a1c3d46eb6724598daa21cf7ae9a83c6012126e840e3f7c665142fb04f
Best match: PyGithub 1.44.1
Processing PyGithub-1.44.1.tar.gz
Writing C:\Users\sndr\AppData\Local\Temp\easy_install-urmy_chi\PyGithub-1.44.1\setup.cfg
Running PyGithub-1.44.1\setup.py -q bdist_egg --dist-dir C:\Users\sndr\AppData\Local\Temp\easy_install-urmy_chi\PyGithub-1.44.1\egg-dist-tmp-hkv3w5ci
zip_safe flag not set; analyzing archive contents...
Copying pygithub-1.44.1-py3.6.egg to c:\users\sndr\anaconda3\lib\site-packages
Adding pygithub 1.44.1 to easy-install.pth file

Installed c:\users\sndr\anaconda3\lib\site-packages\pygithub-1.44.1-py3.6.egg
Searching for pyjwt
Reading https://pypi.org/simple/pyjwt/
Downloading https://files.pythonhosted.org/packages/87/8b/6a9f14b5f781697e51259d81657e6048fd31a113229cf346880bb7545565/PyJWT-1.7.1-py2.py3-none-any.whl#sha256=5c6eca3c2940464d106b99ba83b00c6add741c9becaec087fb7ccdefea71350e
Best match: PyJWT 1.7.1
Processing PyJWT-1.7.1-py2.py3-none-any.whl
Installing PyJWT-1.7.1-py2.py3-none-any.whl to c:\users\sndr\anaconda3\lib\site-packages
writing requirements to c:\users\sndr\anaconda3\lib\site-packages\PyJWT-1.7.1-py3.6.egg\EGG-INFO\requires.txt
Adding PyJWT 1.7.1 to easy-install.pth file
Installing pyjwt-script.py script to C:\Users\sndr\Anaconda3\Scripts
Installing pyjwt.exe script to C:\Users\sndr\Anaconda3\Scripts

Installed c:\users\sndr\anaconda3\lib\site-packages\pyjwt-1.7.1-py3.6.egg
Searching for deprecated
Reading https://pypi.org/simple/deprecated/
Downloading https://files.pythonhosted.org/packages/f6/89/62912e01f3cede11edcc0abf81298e3439d9c06c8dce644369380ed13f6d/Deprecated-1.2.7-py2.py3-none-any.whl#sha256=8b6a5aa50e482d8244a62e5582b96c372e87e3a28e8b49c316e46b95c76a611d
Best match: Deprecated 1.2.7
Processing Deprecated-1.2.7-py2.py3-none-any.whl
Installing Deprecated-1.2.7-py2.py3-none-any.whl to c:\users\sndr\anaconda3\lib\site-packages
writing requirements to c:\users\sndr\anaconda3\lib\site-packages\Deprecated-1.2.7-py3.6.egg\EGG-INFO\requires.txt
Adding Deprecated 1.2.7 to easy-install.pth file

Installed c:\users\sndr\anaconda3\lib\site-packages\deprecated-1.2.7-py3.6.egg
Searching for six==1.11.0
Best match: six 1.11.0
Adding six 1.11.0 to easy-install.pth file

Using c:\users\sndr\anaconda3\lib\site-packages
Searching for requests==2.18.4
Best match: requests 2.18.4
Adding requests 2.18.4 to easy-install.pth file

Using c:\users\sndr\anaconda3\lib\site-packages
Searching for certifi==2019.6.16
Best match: certifi 2019.6.16
Adding certifi 2019.6.16 to easy-install.pth file

Using c:\users\sndr\anaconda3\lib\site-packages
Searching for urllib3==1.22
Best match: urllib3 1.22
Adding urllib3 1.22 to easy-install.pth file

Using c:\users\sndr\anaconda3\lib\site-packages
Searching for idna==2.6
Best match: idna 2.6
Adding idna 2.6 to easy-install.pth file

Using c:\users\sndr\anaconda3\lib\site-packages
Searching for chardet==3.0.4
Best match: chardet 3.0.4
Adding chardet 3.0.4 to easy-install.pth file
Installing chardetect-script.py script to C:\Users\sndr\Anaconda3\Scripts
Installing chardetect.exe script to C:\Users\sndr\Anaconda3\Scripts

Using c:\users\sndr\anaconda3\lib\site-packages
Searching for wrapt==1.10.11
Best match: wrapt 1.10.11
Adding wrapt 1.10.11 to easy-install.pth file

Using c:\users\sndr\anaconda3\lib\site-packages
Finished processing dependencies for gitim==2.1.0

E:\Python usefull packages\gitim-master\gitim-master>
